import { HERITAGE_SOURCE_REFS } from "./constants";
import { resolveImageAsset } from "./image-provider";
import type { F1DriverEntity } from "./types";
import { yearsLabel } from "./utils";

const updatedAt = "2026-06-17T00:00:00.000Z";

type DriverSeed = Omit<
  F1DriverEntity,
  | "mode"
  | "slug"
  | "careerSpanLabel"
  | "totalChampionships"
  | "wins"
  | "poles"
  | "podiums"
  | "fastestLaps"
  | "entries"
  | "image"
  | "artifactIds"
  | "sourceRefs"
  | "updatedAt"
>;

function artifactsForDriver(id: string, hasTitle: boolean) {
  return [
    `driver-${id}-helmet`,
    `driver-${id}-suit`,
    hasTitle ? `driver-${id}-trophy` : `driver-${id}-season-card`,
    `driver-${id}-moment`,
  ];
}

function driver(seed: DriverSeed): F1DriverEntity {
  return {
    ...seed,
    mode: "driver",
    slug: seed.id,
    careerSpanLabel: yearsLabel(seed.debutYear, seed.finalYear, seed.active),
    totalChampionships: seed.championshipYears.length,
    wins: null,
    poles: null,
    podiums: null,
    fastestLaps: null,
    entries: null,
    image: resolveImageAsset(seed.id, "driver", seed.name, "portrait"),
    artifactIds: artifactsForDriver(seed.id, seed.championshipYears.length > 0),
    sourceRefs: [HERITAGE_SOURCE_REFS.seed, HERITAGE_SOURCE_REFS.jolpica],
    updatedAt,
  };
}

export const seedDrivers: F1DriverEntity[] = [
  driver({
    id: "juan-manuel-fangio",
    name: "Juan Manuel Fangio",
    givenName: "Juan Manuel",
    familyName: "Fangio",
    nationality: "Argentine",
    countryCode: "AR",
    dateOfBirth: "1911-06-24",
    debutYear: 1950,
    finalYear: 1958,
    active: false,
    championshipYears: [1951, 1954, 1955, 1956, 1957],
    teams: ["Alfa Romeo", "Maserati", "Mercedes", "Ferrari"],
    primaryEra: "Fangio and the birth of the championship",
    primaryTeam: "Maserati",
    primaryColor: "#c21f26",
    secondaryColor: "#f4ead8",
    helmetColor: "#f3efe4",
    bio30Words:
      "Fangio set the early benchmark for racecraft, mechanical sympathy, and calm authority across F1's most dangerous first decade.",
    longBio:
      "Juan Manuel Fangio remains the original measuring stick of Formula 1 greatness: adaptable across teams, devastatingly precise, and revered by rivals who understood the risk of his era.",
  }),
  driver({
    id: "stirling-moss",
    name: "Stirling Moss",
    givenName: "Stirling",
    familyName: "Moss",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "1929-09-17",
    debutYear: 1951,
    finalYear: 1961,
    active: false,
    championshipYears: [],
    teams: ["Mercedes", "Maserati", "Vanwall", "Lotus"],
    primaryEra: "Fangio and the birth of the championship",
    primaryTeam: "Vanwall",
    primaryColor: "#1f8f5f",
    secondaryColor: "#f4ead8",
    helmetColor: "#f7f1df",
    bio30Words:
      "Moss became the archetypal champion without a crown, celebrated for versatility, speed, and sportsmanship across grand prix and endurance racing.",
    longBio:
      "Stirling Moss never needed a world title to define his status. His reputation rests on relentless speed, technical range, and a competitive code that made him one of Britain's defining racers.",
  }),
  driver({
    id: "jim-clark",
    name: "Jim Clark",
    givenName: "Jim",
    familyName: "Clark",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "1936-03-04",
    debutYear: 1960,
    finalYear: 1968,
    active: false,
    championshipYears: [1963, 1965],
    teams: ["Lotus"],
    primaryEra: "British garagistes and Lotus innovation",
    primaryTeam: "Lotus",
    primaryColor: "#1f6f43",
    secondaryColor: "#f6d04d",
    helmetColor: "#0f172a",
    bio30Words:
      "Clark fused delicacy and impossible pace, turning Lotus innovation into some of the cleanest domination Formula 1 has seen.",
    longBio:
      "Jim Clark's style was quiet and almost frictionless. In the Lotus years he made technical fragility look composed, winning with a margin and elegance that still feels modern.",
  }),
  driver({
    id: "jackie-stewart",
    name: "Jackie Stewart",
    givenName: "Jackie",
    familyName: "Stewart",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "1939-06-11",
    debutYear: 1965,
    finalYear: 1973,
    active: false,
    championshipYears: [1969, 1971, 1973],
    teams: ["BRM", "Matra", "Tyrrell"],
    primaryEra: "Wings, risk, and Ferrari resurgence",
    primaryTeam: "Tyrrell",
    primaryColor: "#244c9a",
    secondaryColor: "#f4ead8",
    helmetColor: "#f4ead8",
    bio30Words:
      "Stewart paired champion precision with a public safety campaign that helped move Formula 1 toward professional modernity.",
    longBio:
      "Jackie Stewart was ruthless in the cockpit and just as determined outside it. His championship years and safety advocacy changed how Formula 1 understood excellence and responsibility.",
  }),
  driver({
    id: "niki-lauda",
    name: "Niki Lauda",
    givenName: "Niki",
    familyName: "Lauda",
    nationality: "Austrian",
    countryCode: "AT",
    dateOfBirth: "1949-02-22",
    debutYear: 1971,
    finalYear: 1985,
    active: false,
    championshipYears: [1975, 1977, 1984],
    teams: ["Ferrari", "Brabham", "McLaren"],
    primaryEra: "Ground effects and turbo wars",
    primaryTeam: "Ferrari",
    primaryColor: "#b91c1c",
    secondaryColor: "#f4ead8",
    helmetColor: "#dc2626",
    bio30Words:
      "Lauda made calculation heroic, turning technical feedback, discipline, and resilience into three titles across two distinct F1 lives.",
    longBio:
      "Niki Lauda's legend is built from intelligence as much as bravery. He turned cars into systems he could solve, then returned from trauma to win again with unsentimental force.",
  }),
  driver({
    id: "james-hunt",
    name: "James Hunt",
    givenName: "James",
    familyName: "Hunt",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "1947-08-29",
    debutYear: 1973,
    finalYear: 1979,
    active: false,
    championshipYears: [1976],
    teams: ["Hesketh", "McLaren", "Wolf"],
    primaryEra: "Wings, risk, and Ferrari resurgence",
    primaryTeam: "McLaren",
    primaryColor: "#f97316",
    secondaryColor: "#111111",
    helmetColor: "#f4ead8",
    bio30Words:
      "Hunt's 1976 crown brought instinct, volatility, and charisma into one of Formula 1's most cinematic championship fights.",
    longBio:
      "James Hunt drove with raw improvisational force. His championship season against Lauda became a defining rivalry because it carried danger, contrast, and a human edge beyond timing sheets.",
  }),
  driver({
    id: "alain-prost",
    name: "Alain Prost",
    givenName: "Alain",
    familyName: "Prost",
    nationality: "French",
    countryCode: "FR",
    dateOfBirth: "1955-02-24",
    debutYear: 1980,
    finalYear: 1993,
    active: false,
    championshipYears: [1985, 1986, 1989, 1993],
    teams: ["McLaren", "Renault", "Ferrari", "Williams"],
    primaryEra: "Senna, Prost, and McLaren dominance",
    primaryTeam: "McLaren",
    primaryColor: "#f97316",
    secondaryColor: "#f4ead8",
    helmetColor: "#f4ead8",
    bio30Words:
      "Prost turned patience, tire craft, and exact calculation into a championship language that was as punishing as outright aggression.",
    longBio:
      "Alain Prost's nickname, the Professor, fits because his victories often looked pre-planned. He understood races as evolving equations and made restraint feel lethal.",
  }),
  driver({
    id: "ayrton-senna",
    name: "Ayrton Senna",
    givenName: "Ayrton",
    familyName: "Senna",
    nationality: "Brazilian",
    countryCode: "BR",
    dateOfBirth: "1960-03-21",
    debutYear: 1984,
    finalYear: 1994,
    active: false,
    championshipYears: [1988, 1990, 1991],
    teams: ["Toleman", "Lotus", "McLaren", "Williams"],
    primaryEra: "Senna, Prost, and McLaren dominance",
    primaryTeam: "McLaren",
    primaryColor: "#f5d04a",
    secondaryColor: "#0f8a3a",
    helmetColor: "#f7d116",
    bio30Words:
      "Senna made qualifying laps feel spiritual, blending ferocious belief, wet-weather genius, and fragile brilliance into an enduring mythology.",
    longBio:
      "Ayrton Senna's appeal comes from more than speed. He raced as if every limit were negotiable, and his intensity made moments of perfection feel almost theatrical.",
  }),
  driver({
    id: "nigel-mansell",
    name: "Nigel Mansell",
    givenName: "Nigel",
    familyName: "Mansell",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "1953-08-08",
    debutYear: 1980,
    finalYear: 1995,
    active: false,
    championshipYears: [1992],
    teams: ["Lotus", "Williams", "Ferrari", "McLaren"],
    primaryEra: "Senna, Prost, and McLaren dominance",
    primaryTeam: "Williams",
    primaryColor: "#1d4ed8",
    secondaryColor: "#f4ead8",
    helmetColor: "#1d4ed8",
    bio30Words:
      "Mansell's title season rewarded years of commitment, heavy steering, huge commitment, and a public appetite for flat-out bravery.",
    longBio:
      "Nigel Mansell turned effort into spectacle. His 1992 Williams campaign was dominant, but his wider appeal came from visibly wrestling the car and the moment.",
  }),
  driver({
    id: "michael-schumacher",
    name: "Michael Schumacher",
    givenName: "Michael",
    familyName: "Schumacher",
    nationality: "German",
    countryCode: "DE",
    dateOfBirth: "1969-01-03",
    debutYear: 1991,
    finalYear: 2012,
    active: false,
    championshipYears: [1994, 1995, 2000, 2001, 2002, 2003, 2004],
    teams: ["Jordan", "Benetton", "Ferrari", "Mercedes"],
    primaryEra: "Schumacher era",
    primaryTeam: "Ferrari",
    primaryColor: "#b91c1c",
    secondaryColor: "#f4ead8",
    helmetColor: "#dc2626",
    bio30Words:
      "Schumacher industrialized domination, joining relentless fitness, strategy, testing, and Ferrari unity into a modern dynasty.",
    longBio:
      "Michael Schumacher remade what a Formula 1 driver could demand from a team. His Ferrari years fused speed, preparation, and institutional obsession into a benchmark era.",
  }),
  driver({
    id: "mika-hakkinen",
    name: "Mika Hakkinen",
    givenName: "Mika",
    familyName: "Hakkinen",
    nationality: "Finnish",
    countryCode: "FI",
    dateOfBirth: "1968-09-28",
    debutYear: 1991,
    finalYear: 2001,
    active: false,
    championshipYears: [1998, 1999],
    teams: ["Lotus", "McLaren"],
    primaryEra: "Schumacher era",
    primaryTeam: "McLaren",
    primaryColor: "#c0c7d1",
    secondaryColor: "#111111",
    helmetColor: "#f4ead8",
    bio30Words:
      "Hakkinen answered Schumacher with cool precision, devastating qualifying speed, and a calmness that made pressure seem quieter.",
    longBio:
      "Mika Hakkinen's title fights carried a restrained intensity. At his best he was beautifully economical: exact in qualifying, clean in combat, and trusted by McLaren completely.",
  }),
  driver({
    id: "fernando-alonso",
    name: "Fernando Alonso",
    givenName: "Fernando",
    familyName: "Alonso",
    nationality: "Spanish",
    countryCode: "ES",
    dateOfBirth: "1981-07-29",
    debutYear: 2001,
    finalYear: null,
    active: true,
    championshipYears: [2005, 2006],
    teams: ["Minardi", "Renault", "McLaren", "Ferrari", "Alpine", "Aston Martin"],
    primaryEra: "Renault, Ferrari, Brawn, and Red Bull rise",
    primaryTeam: "Renault",
    primaryColor: "#2563eb",
    secondaryColor: "#f4d35e",
    helmetColor: "#2563eb",
    bio30Words:
      "Alonso's longevity rests on race intelligence, adaptive aggression, and the ability to drag complicated cars toward unlikely results.",
    longBio:
      "Fernando Alonso has lived several Formula 1 careers inside one. His Renault titles ended Schumacher's run, and his later seasons have emphasized craft, race reading, and endurance.",
  }),
  driver({
    id: "kimi-raikkonen",
    name: "Kimi Raikkonen",
    givenName: "Kimi",
    familyName: "Raikkonen",
    nationality: "Finnish",
    countryCode: "FI",
    dateOfBirth: "1979-10-17",
    debutYear: 2001,
    finalYear: 2021,
    active: false,
    championshipYears: [2007],
    teams: ["Sauber", "McLaren", "Ferrari", "Lotus", "Alfa Romeo"],
    primaryEra: "Renault, Ferrari, Brawn, and Red Bull rise",
    primaryTeam: "Ferrari",
    primaryColor: "#b91c1c",
    secondaryColor: "#f4ead8",
    helmetColor: "#f4ead8",
    bio30Words:
      "Raikkonen combined minimalist public theatre with pure speed, winning Ferrari's most recent drivers' title through late-season precision.",
    longBio:
      "Kimi Raikkonen's appeal came from removing noise. The driving was direct, instinctive, and fast, with a 2007 title that rewarded opportunism and ice-cool execution.",
  }),
  driver({
    id: "sebastian-vettel",
    name: "Sebastian Vettel",
    givenName: "Sebastian",
    familyName: "Vettel",
    nationality: "German",
    countryCode: "DE",
    dateOfBirth: "1987-07-03",
    debutYear: 2007,
    finalYear: 2022,
    active: false,
    championshipYears: [2010, 2011, 2012, 2013],
    teams: ["BMW Sauber", "Toro Rosso", "Red Bull Racing", "Ferrari", "Aston Martin"],
    primaryEra: "Renault, Ferrari, Brawn, and Red Bull rise",
    primaryTeam: "Red Bull Racing",
    primaryColor: "#1e3a8a",
    secondaryColor: "#facc15",
    helmetColor: "#f4d35e",
    bio30Words:
      "Vettel maximized Red Bull's aero peak with relentless starts, metronomic race control, and a young champion's hunger.",
    longBio:
      "Sebastian Vettel's Red Bull years were about qualifying command, clean air, and surgical execution. Later, his Ferrari and Aston Martin chapters revealed reflection and advocacy.",
  }),
  driver({
    id: "lewis-hamilton",
    name: "Lewis Hamilton",
    givenName: "Lewis",
    familyName: "Hamilton",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "1985-01-07",
    debutYear: 2007,
    finalYear: null,
    active: true,
    championshipYears: [2008, 2014, 2015, 2017, 2018, 2019, 2020],
    teams: ["McLaren", "Mercedes", "Ferrari"],
    primaryEra: "Hybrid Mercedes era",
    primaryTeam: "Mercedes",
    primaryColor: "#14b8a6",
    secondaryColor: "#111111",
    helmetColor: "#7c3aed",
    bio30Words:
      "Hamilton fused record-breaking speed with cultural reach, turning the hybrid era into both sporting dominance and a broader platform.",
    longBio:
      "Lewis Hamilton's career spans instant rookie brilliance, McLaren pressure, Mercedes domination, and a continued hunger to redefine what a champion can represent.",
  }),
  driver({
    id: "max-verstappen",
    name: "Max Verstappen",
    givenName: "Max",
    familyName: "Verstappen",
    nationality: "Dutch",
    countryCode: "NL",
    dateOfBirth: "1997-09-30",
    debutYear: 2015,
    finalYear: null,
    active: true,
    championshipYears: [2021, 2022, 2023, 2024],
    teams: ["Toro Rosso", "Red Bull Racing"],
    primaryEra: "Ground-effect modern era",
    primaryTeam: "Red Bull Racing",
    primaryColor: "#1d2d6b",
    secondaryColor: "#ef4444",
    helmetColor: "#f97316",
    bio30Words:
      "Verstappen made modern dominance look blunt and inevitable, pairing early aggression with extraordinary control under ground-effect regulations.",
    longBio:
      "Max Verstappen's rise reshaped Red Bull's modern identity. His peak combines ruthless race pace, defensive certainty, and an unusually direct connection to car behavior.",
  }),
  driver({
    id: "charles-leclerc",
    name: "Charles Leclerc",
    givenName: "Charles",
    familyName: "Leclerc",
    nationality: "Monegasque",
    countryCode: "MC",
    dateOfBirth: "1997-10-16",
    debutYear: 2018,
    finalYear: null,
    active: true,
    championshipYears: [],
    teams: ["Sauber", "Ferrari"],
    primaryEra: "Ground-effect modern era",
    primaryTeam: "Ferrari",
    primaryColor: "#b91c1c",
    secondaryColor: "#f4ead8",
    helmetColor: "#dc2626",
    bio30Words:
      "Leclerc brings qualifying voltage and emotional Ferrari theatre, often turning narrow windows into memorable laps.",
    longBio:
      "Charles Leclerc's Ferrari story is still being written. His best performances are defined by precision over one lap, intense race craft, and the weight of expectation.",
  }),
  driver({
    id: "lando-norris",
    name: "Lando Norris",
    givenName: "Lando",
    familyName: "Norris",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "1999-11-13",
    debutYear: 2019,
    finalYear: null,
    active: true,
    championshipYears: [2025],
    teams: ["McLaren"],
    primaryEra: "Ground-effect modern era",
    primaryTeam: "McLaren",
    primaryColor: "#f97316",
    secondaryColor: "#111111",
    helmetColor: "#f97316",
    bio30Words:
      "Norris represents McLaren's modern resurgence: fast, adaptive, media-native, and increasingly capable of turning promise into title pressure.",
    longBio:
      "Lando Norris has grown with McLaren's return to the front. His arc captures a newer F1 generation: technically sharp, publicly open, and now central to the team's revived identity.",
  }),
];
